mutation removeSchool($parentId: ID!, $childId: ID!) {
  RemoveSchoolClassSchool(
    from: { schoolClassId: $parentId }
    to: { schoolId: $childId }
  ) {
    from {
      schoolClassId
    }
    to {
      schoolId
    }
  }
}
