mutation mergeKnowledgeArea($parentId: ID!, $childId: ID!) {
  MergeAssessmentKnowledgeArea(
    from: { id: $parentId }
    to: { knowledgeAreaId: $childId }
  ) {
    from {
      id
    }
    to {
      knowledgeAreaId
    }
  }
}
