mutation removeSchoolClass($parentId: ID!, $childId: ID!) {
  RemoveAssessmentSchoolClass(
    from: { id: $parentId }
    to: { schoolClassId: $childId }
  ) {
    from {
      id
    }
    to {
      schoolClassId
    }
  }
}
