mutation UpdateSchool(
  $Id: ID!
  $name: String
  $normalizedName: String!
  $code: String
  $cnpj: String
  $city: String
  $avatarUrl: String
  $isFrozen: Boolean
  $isOnNationalOlympics: Boolean
  $clientStatus: ClientStatus
  $updatedAt: _Neo4jDateTimeInput!
  $trialStartDate: _Neo4jDateTimeInput
  $trialEndDate: _Neo4jDateTimeInput
) {
  UpdateSchool(
    schoolId: $Id
    name: $name
    normalizedName: $normalizedName
    code: $code
    cnpj: $cnpj
    city: $city
    avatarUrl: $avatarUrl
    isFrozen: $isFrozen
    isOnNationalOlympics: $isOnNationalOlympics
    clientStatus: $clientStatus
    updatedAt: $updatedAt
    trialStartDate: $trialStartDate
    trialEndDate: $trialEndDate
  ) {
    schoolId
  }
}
