#import "./fragment.gql"

query TaskList(
  $id: ID!
) {
Task(
    id: $id
  ) {
    ...Task
    status
    createdAt {formatted}
    creator {
      id
      email
      whatsappNumber
    }
    schoolClass {
      name
    }
  }
}