mutation registerStudentWithExternalId(
  $email: String!
  $name: String!
  $externalId: String
  $schoolClassId: ID
) {
  registerStudentExternalId(
    email: $email
    name: $name
    externalId: $externalId
    schoolClassId: $schoolClassId
  ) {
    id
  }
}
