mutation UpdateStudent(
  $Id: ID!
  $name: String
  $normalizedName: String!
  $nickname: String
  $schoolYear: Int
  $birthday: _Neo4jDateTimeInput
  $email: String
  $parentFullName: String
  $avatarUrl: String
  $password: String
  $updatedAt: _Neo4jDateTimeInput!
) {
  UpdateStudent(
    id: $Id
    name: $name
    normalizedName: $normalizedName
    nickname: $nickname
    schoolYear: $schoolYear
    birthday: $birthday
    email: $email
    parentFullName: $parentFullName
    avatarUrl: $avatarUrl
    password: $password
    updatedAt: $updatedAt
  ) {
    id
  }
}
